
Parameters:
  Owner:
    Type: String
    Description: An email address of who is creating this AWS stack - for tagging
    Default: admin@thisaccount.com
    MinLength: '4'


Resources:
  BuildkiteSecretsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-buildkite-secrets"
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName} Buildkite Secrets"
      - Key: Owner
        Value: !Ref Owner


  BuildkiteSecretsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'BuildkiteSecretsBucket'
      PolicyDocument:
        Statement:
          - Sid: List
            Action:
              - s3:ListBucket
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${BuildkiteSecretsBucket}'
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                # maybe the other accounts here
          - Sid: Read
            Action:
              - s3:Get*
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${BuildkiteSecretsBucket}/*'
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                # maybe the other accounts here
          - Sid: Write
            Action:
              - s3:Put*
            Effect: Deny
            Resource: !Sub 'arn:aws:s3:::${BuildkiteSecretsBucket}/*'
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: aws:kms
                # demand kms put into the bucket
          - Sid: Write
            Action:
              - s3:Put*
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${BuildkiteSecretsBucket}/*'
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                # maybe people who need to upload keys here too
