
Parameters:
  Owner:
    Type: String
    Description: An email address of who is creating this AWS stack - for tagging
    Default: admin@thisaccount.com
    MinLength: '4'
  VPCStackName:
    Type: String
    Description: The name of the vpc stack that is then used to construct ImportValue values
    Default: tnh-vpc
  BuildName:
    Type: String
    Description: The name of the code build job
    Default: example-build-job


Resources:
    CodeBuildServicetRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "codebuild.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Path: "/service-role/"
        Policies:
          -
            PolicyName: "codebuild"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeDhcpOptions
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                    - ec2:DescribeSubnets
                    - ec2:DescribeSecurityGroups
                    - ec2:DescribeVpcs
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterfacePermission
                  Resource:
                    - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*"
                  Condition:
                    StringEquals:
                      ec2:Subnet:
                        - !Join [ "", [ "arn:aws:ec2:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId",  ":subnet/",   !Select ['0', !Split [',', !ImportValue {'Fn::Sub': '${VPCStackName}-InternalSubnets'}]] ]]
                        - !Join [ "", [ "arn:aws:ec2:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId",  ":subnet/",   !Select ['1', !Split [',', !ImportValue {'Fn::Sub': '${VPCStackName}-InternalSubnets'}]] ]]
                      ec2:AuthorizedService: codebuild.amazonaws.com
                - Effect: Allow
                  Resource:
                    - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:GetObjectVersion
                - Effect: Allow
                  Action:
                    - ssm:GetParameters
                  Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CodeBuild/*"

    CodeBuildSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Codebuild Security Group
        VpcId: !ImportValue
               Fn::Sub: ${VPCStackName}-VpcId

    CodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: !Ref BuildName
        Description: A description about my project
        ServiceRole: !GetAtt CodeBuildServicetRole.Arn
        Artifacts:
          Type: no_artifacts
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/java:openjdk-8
          EnvironmentVariables:
          - Name: something
            Value: somevalue
        Source:
          Auth:
            Type: OAUTH
            Resource: "dontknow" 
          Location: https://github.com/tnh/cloudformation-snippets.git
          Type: GITHUB
        TimeoutInMinutes: 10
        VpcConfig:
          VpcId: !ImportValue
                 Fn::Sub: ${VPCStackName}-VpcId
          Subnets: !Split [',', !ImportValue {'Fn::Sub': '${VPCStackName}-InternalSubnets'}]
          SecurityGroupIds:
          - !Ref CodeBuildSecurityGroup

        Tags:
          - Key: Name
            Value: example-build-job
          - Key: Owner
            Value: Value2
